import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavigationBar from "@/components/NavigationBar";
import Provider from "@/components/Provider";
import { getServerSession } from "next-auth";
import { addUserToDb } from "@/libs/addUserToDb";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession()
  if (session) await addUserToDb()

  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Provider>
        <NavigationBar/>
        {children}
        </Provider>
        </body>
    </html>
  );
}
